
server:
  port: 8092
spring:
  application:
    name: qctivemq
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: false
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://wangyang:123456@127.0.0.1:18761/eureka/
activemq:
  queueName: mailboxQueue
  topicName: mailboxTopic